export default {
  CONNECTION_STATES: {
    CONNECTED: 1,
    RECONNECTING: 2,
    DISCONNECTED: 3,
  },
  COLORS: {
    LIGHT_BLUE_BORDER: '#D9E5ED',
    LIGHT_BLUE_BACKGROUND: '#EDF3F6',
    BRIGHT_BLUE: '#5398E7',
    GREY_BLUE: '#7293A7',
    DARK_GREY: '#254351',
  },
};
